name: Build project and deploy to SmarterASP.NET
on: [push]

jobs:
  build_and_deploy:
    name: Build package and deploy to SmarterASP.NET
    runs-on: windows-latest
    steps:
      - name: build file
        uses: actions/checkout@v1

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: win6055.site4now.net
          username: arthrasarkos-001
          password: @lala1905A
